# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://fifihenry.github.io/dpfs/#services
title: Fifi for DPFS
email: fifihenry73@gmail.com
author: Fifi Henry
description: > # "Write an awesome description for your new site here. 
  Vote Fifi for DPFS!
copyright: 'Copyright &copy; 2019 Fifi Henry. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: facebook
    url: https://www.facebook.com/events/415297635914104
  - title: instagram
    url: http://instagram.com/fifi_for_dpfs
